// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: db.proto

package protobook

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vspc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	TxIds         [][]byte               `protobuf:"bytes,2,rep,name=txIds,proto3" json:"txIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vspc) Reset() {
	*x = Vspc{}
	mi := &file_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vspc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vspc) ProtoMessage() {}

func (x *Vspc) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vspc.ProtoReflect.Descriptor instead.
func (*Vspc) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{0}
}

func (x *Vspc) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Vspc) GetTxIds() [][]byte {
	if x != nil {
		return x.TxIds
	}
	return nil
}

type Block struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Hash                 []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	DaaScore             uint64                 `protobuf:"varint,2,opt,name=daaScore,proto3" json:"daaScore,omitempty"`
	BlueScore            uint64                 `protobuf:"varint,3,opt,name=blueScore,proto3" json:"blueScore,omitempty"`
	Timestamp            uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AcceptedIdMerkleRoot []byte                 `protobuf:"bytes,5,opt,name=acceptedIdMerkleRoot,proto3" json:"acceptedIdMerkleRoot,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{1}
}

func (x *Block) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Block) GetDaaScore() uint64 {
	if x != nil {
		return x.DaaScore
	}
	return 0
}

func (x *Block) GetBlueScore() uint64 {
	if x != nil {
		return x.BlueScore
	}
	return 0
}

func (x *Block) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Block) GetAcceptedIdMerkleRoot() []byte {
	if x != nil {
		return x.AcceptedIdMerkleRoot
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          []byte                 `protobuf:"bytes,1,opt,name=txId,proto3" json:"txId,omitempty"`
	TxHash        []byte                 `protobuf:"bytes,2,opt,name=txHash,proto3" json:"txHash,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,3,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	BlockTime     uint64                 `protobuf:"varint,4,opt,name=blockTime,proto3" json:"blockTime,omitempty"`
	Inputs        []*TransactionInput    `protobuf:"bytes,5,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs       []*TransactionOutput   `protobuf:"bytes,6,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_db_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetTxId() []byte {
	if x != nil {
		return x.TxId
	}
	return nil
}

func (x *Transaction) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *Transaction) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *Transaction) GetBlockTime() uint64 {
	if x != nil {
		return x.BlockTime
	}
	return 0
}

func (x *Transaction) GetInputs() []*TransactionInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Transaction) GetOutputs() []*TransactionOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type TransactionInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrevTxId      []byte                 `protobuf:"bytes,1,opt,name=prevTxId,proto3" json:"prevTxId,omitempty"`
	PrevTxIndex   uint32                 `protobuf:"varint,2,opt,name=prevTxIndex,proto3" json:"prevTxIndex,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Amount        uint64                 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionInput) Reset() {
	*x = TransactionInput{}
	mi := &file_db_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInput) ProtoMessage() {}

func (x *TransactionInput) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInput.ProtoReflect.Descriptor instead.
func (*TransactionInput) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionInput) GetPrevTxId() []byte {
	if x != nil {
		return x.PrevTxId
	}
	return nil
}

func (x *TransactionInput) GetPrevTxIndex() uint32 {
	if x != nil {
		return x.PrevTxIndex
	}
	return 0
}

func (x *TransactionInput) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TransactionInput) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TransactionOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionOutput) Reset() {
	*x = TransactionOutput{}
	mi := &file_db_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionOutput) ProtoMessage() {}

func (x *TransactionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionOutput.ProtoReflect.Descriptor instead.
func (*TransactionOutput) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionOutput) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TransactionOutput) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_db_proto protoreflect.FileDescriptor

const file_db_proto_rawDesc = "" +
	"\n" +
	"\bdb.proto\x12\tprotobook\"0\n" +
	"\x04Vspc\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x14\n" +
	"\x05txIds\x18\x02 \x03(\fR\x05txIds\"\xa7\x01\n" +
	"\x05Block\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x1a\n" +
	"\bdaaScore\x18\x02 \x01(\x04R\bdaaScore\x12\x1c\n" +
	"\tblueScore\x18\x03 \x01(\x04R\tblueScore\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x122\n" +
	"\x14acceptedIdMerkleRoot\x18\x05 \x01(\fR\x14acceptedIdMerkleRoot\"\xe2\x01\n" +
	"\vTransaction\x12\x12\n" +
	"\x04txId\x18\x01 \x01(\fR\x04txId\x12\x16\n" +
	"\x06txHash\x18\x02 \x01(\fR\x06txHash\x12\x1c\n" +
	"\tblockHash\x18\x03 \x01(\fR\tblockHash\x12\x1c\n" +
	"\tblockTime\x18\x04 \x01(\x04R\tblockTime\x123\n" +
	"\x06inputs\x18\x05 \x03(\v2\x1b.protobook.TransactionInputR\x06inputs\x126\n" +
	"\aoutputs\x18\x06 \x03(\v2\x1c.protobook.TransactionOutputR\aoutputs\"\x82\x01\n" +
	"\x10TransactionInput\x12\x1a\n" +
	"\bprevTxId\x18\x01 \x01(\fR\bprevTxId\x12 \n" +
	"\vprevTxIndex\x18\x02 \x01(\rR\vprevTxIndex\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x04R\x06amount\"E\n" +
	"\x11TransactionOutput\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amountB\rZ\v.;protobookb\x06proto3"

var (
	file_db_proto_rawDescOnce sync.Once
	file_db_proto_rawDescData []byte
)

func file_db_proto_rawDescGZIP() []byte {
	file_db_proto_rawDescOnce.Do(func() {
		file_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_db_proto_rawDesc), len(file_db_proto_rawDesc)))
	})
	return file_db_proto_rawDescData
}

var file_db_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_db_proto_goTypes = []any{
	(*Vspc)(nil),              // 0: protobook.Vspc
	(*Block)(nil),             // 1: protobook.Block
	(*Transaction)(nil),       // 2: protobook.Transaction
	(*TransactionInput)(nil),  // 3: protobook.TransactionInput
	(*TransactionOutput)(nil), // 4: protobook.TransactionOutput
}
var file_db_proto_depIdxs = []int32{
	3, // 0: protobook.Transaction.inputs:type_name -> protobook.TransactionInput
	4, // 1: protobook.Transaction.outputs:type_name -> protobook.TransactionOutput
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_db_proto_init() }
func file_db_proto_init() {
	if File_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_db_proto_rawDesc), len(file_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_db_proto_goTypes,
		DependencyIndexes: file_db_proto_depIdxs,
		MessageInfos:      file_db_proto_msgTypes,
	}.Build()
	File_db_proto = out.File
	file_db_proto_goTypes = nil
	file_db_proto_depIdxs = nil
}
